### ISSUE TITLE
Specdm compatibility

### ISSUE THREAD

**Issue by mexikoedi** [AaronMcKenney/ttt2-role_bank#1]
If the banker dies and spawns in specdm then this issues will appear:
The popup about the banker death is still appearing in specdm. The speed-/damagermodifier is also still active in specdm.

Maybe this code can help: https://github.com/mexikoedi/ttt2_role_med/blob/5b5e4948263951bc611f2df378ba778a24cf1f79/ttt2_role_med/lua/terrortown/entities/roles/medic/shared.lua#L94

Or this discussion: https://github.com/AaronMcKenney/ttt2-role_beac/issues/2

There are also many other roles or addons which support the specdm. For example the roles blight and executioner.

**Comment by AaronMcKenney** [comment]
I see. Speed and damage modifier is understandable, pop-up less so. The pop-up is meant to inform everyone, so if a spectator revives they may want to act on it?

**Comment by mexikoedi** [comment]
Yep.
The popup should not work in specdm.
The popup is displayed for everyone everytime the banker dies in specdm.

The mentioned code will only prevent the popup in specdm (needs to be modified). Otherwise it will work fine if the banker is alive and dies in the round. 
The spectator and specdm guys will still see the popup if the banker dies in the round. And that's good. Only if the banker joins the specdm then it shouldn't appear if he dies there.

I hope i explained it well. Maybe it's a bit weird to explain if you haven't used specdm.

**Comment by AaronMcKenney** [comment]
So essentially, the pop-up is being sent when the Banker dies during spectator deathmatch? Meaning that everyone might see the pop-up several times despite the Banker already being dead in the IRL TTT2 game?

**Comment by mexikoedi** [comment]
Exactly.
The medic role or the blight role use popups too and fixed it that way like i mentioned above. (link to code)

**Comment by AaronMcKenney** [comment]
Ok, so I'm running into an interesting issue here. I can disable the popups, and but the speed isn't being handled correctly. Explicitly, there is some inconsistency in that the speed sometimes gets stuck to the banker's speed. For example, if I set ttt2_banker_speed_multi to 0.1, the Banker moves at a crawl. Sometimes this means that the "ghost" in spectator DM will also move at a crawl, but not always. It seems to be the case that if I check for IsGhost() in the TTTPlayerSpeedModifier hook, the Ghost's speed will always be set to the Banker's speed. No idea why, the hook won't even get called. Would you happen to know why this is the case?

**Comment by mexikoedi** [comment]
Weird. I will look into it later. 

Maybe look into the specdm code here, this might help: https://github.com/TheNickSkater/TTT_Spectator_Deathmatch/blob/7d7f49e5c2bb7f94d358b9b455ce34e4c490c566/lua/sh_spectator_deathmatch.lua#L57

The movement speed is handled there.

**Comment by mexikoedi** [comment]
I think i fixed it quite well with the speed, stamina and damage. 
Should i include it here or should i do a pr?

**Comment by AaronMcKenney** [comment]
Wait, from that code you posted I noticed a couple things.

Firstly, I noticed an issue in the code you linked:

```lua
        -- fix 1 for speedmodifier (shinigami speed fix)
        if ply:GetSubRole() == ROLE_SHINIGAMI then
            mul = basemul * mul * noLag[1] / 2
        end
```

You divide by two here, but it should be divided by ttt2_shinigami_speed.

Secondly, why hardcode? Why not just overwrite whatever speed the player currently has with the speed you want, as opposed to trying to negate the speed modifier that every mod offers?

**Comment by mexikoedi** [comment]
It should be 2, if ttt2_shinigami_speed would be used then the shinigami would be faster or slower if the convar is changed and that would be not good because he needs to be always the same speed like all the others in specdm so the convar can't be used there. 
Also there were no issues regarding the shinigami.
Other roles have also no problem with the speedmodifier provided there.

The speedmodifier was always done so in specdm and the speedmofier was broken until a few weeks ago. 
This line of code is there to fix issues with the shinigami speed and the noLag error. 
Other solutions like setting a speed for walking, running,... have ended in weird behaviors in active rounds (yes there were checks made). 

The solution with the shinigami fix and all other changes regarding the speedmofier and the other changes which were made were also reviewed and approved.


But this is not related to this issue here. I would appreciate it if we would stay on topic.

**Comment by AaronMcKenney** [comment]
But it is related. When I first made the Beacon, I based the speed calculations on the Shinigami itself. When I made the Banker, I reused the code once again. All three of these roles implement movement speed buffs in the same manner, by using the TTTPlayerSpeedModifier hook. How can it not be related? Unless you're referring to the pop-up issue only, and care less about the speed stuff.

Continuing, I have more info to report. Firstly, I notice that when the Shinigami (post 2nd death) enters Spectator Death Match, they are without a weapon. Secondly, I noticed that when I do modify ttt2_shinigami_speed to be a different value (I chose 10 for quick visual inspection) this results in the ghost moving faster than normal. This is very interesting, because the same cannot be said for the Beacon/Banker. Those two roles only move faster/slower if I deliberately add checks to make sure that they aren't ghosts (which is extremely confusing to me, as the code block for all three roles is small and similar. Not sure what could be causing the difference there).

I'm not sure what to make of your first paragraph. It doesn't make sense that using a flat value of 2 would work for all values of ttt2_shinigami_speed, and a quick debug session on my end has proved that. Why can't you just divide by the ConVar? Why can't the ConVar be used?

"Other roles have also no problem with the speedmodifier provided there." ==> Really doesn't make sense, as I have pointed out issues for speed in Banker/Beacon with regards to SpecDM, and I definitely see an issue for the Shinigami as well.

This got a bit lengthy, but anyways you mentioned earlier that you had a potential fix? I can look at it if you think it will work. Alternatively, I could just limit myself to fixing the non-speed stuff for now?

**Comment by mexikoedi** [comment]
I apologise. It is related but the speedmodifier in specdm works like it should.

The bug with no weapons is fixed in a pr at the shinigami repo. 
The convar of shinigami and the convars of beacon had an impact in my testing. I don't know why you are getting different results.

The value changes the speed of the shinigami and if it's higher the guy will be slower in specdm, if it's less than the guy is faster in specdm. All players should be the same speed in specdm, that's why the convar can't be used because it could make him faster or slower.

It makes sense, only some are still buggy like they have some issues with popups or some different issues, but all roles are now fixed or have received a pr. Shinigami is fixed at the moment, only the weapons bug is not fixed because it's not merged right now. Your beacon role and banker role have no checks for specdm, that's why they make problems. 

 I will create an pr and you can add you popup fix there too. Then please test it and see if you are happy about it. The same fixes can be applied for the beacon to fix the hud and buffs there. Needs to be modifed a bit but yeah. 
 
 I really don't want to argue here about the specdm much. I just wanted that these two roles are fixed in specdm. I was really annoyed that the specdm was buggy and roles too so i try to fix these issues. The specdm is good now. (code is still trash but better than before) Most of the roles are fixed or will be fixed if the prs are merged. Sorry if i sound harsh or so, i have no issues with you, i just want to fix these things. You can try the pr with you popup fix and if it's good then you can use it for the beacon in a similar way (the fixes are just simple checks). I also apologise if my english is a bit weird, I haven't checked this text here for grammar or character mistakes. (I am german.)

**Comment by AaronMcKenney** [comment]
That's fine. If it seems like I'm making a fuss it's just because I don't like hardcoding in general, but I understand that it's often a necessary evil. I will fix what I can.

If I may, can I offer an idea? It might save some headaches if you just make it so that a ghost switches roles to something new (Would say "Ghost", but that's technically taken...) and cannot revive again until round's end. This takes away some usability of the mod (The Restless can no longer use death match to clown around between lives, and a Traitor has to decide if they would rather enter DM early or hope that they will be revived by their fellow traitor via defib), but it would also save a lot of headaches. Less of a need to worry about mod compatibility.

**Comment by mexikoedi** [comment]
Thank you for your idea. 
I have noted it down.
Yeah, it would cause some bugs for sure. Like you said and maybe if people try to revive you with a defi or for the necro or so. But yeah, thanks for you idea. 

If there is anything else in regard of the issue or pr then you can just comment. If not feel free to close then.
Quite a lot of comments here :)

**Comment by AaronMcKenney** [comment]
Pop up should be fixed in this commit:
https://github.com/AaronMcKenney/ttt2-role_bank/commit/a65539b6ce670db386cff5c8fb407860e578c7a1

**Comment by mexikoedi** [comment]
Yep, works good. Thank you.
